from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, Image, HRFlowable
from io import BytesIO
import datetime
import os

# Brand Colors (Orange + Black Theme)
PRIMARY = colors.HexColor("#FF6B00")
DARK = colors.HexColor("#111111")
GRAY = colors.HexColor("#6B7280")
LIGHT_GRAY = colors.HexColor("#F9FAFB")

def clean_text(text):
    """Removes unwanted characters like '■' and cleans up whitespace."""
    if not text:
        return ""
    if not isinstance(text, str):
        text = str(text)
    return text.replace("■", "").strip()

def add_footer(canvas, doc):
    canvas.saveState()
    canvas.setFont('Helvetica', 9)
    canvas.setFillColor(GRAY)
    canvas.drawString(50, 30, f"Generated by TravelBNB ✈️  |  {datetime.datetime.now().strftime('%d %b %Y')}")
    canvas.drawRightString(A4[0] - 50, 30, f"Page {doc.page}")
    canvas.restoreState()

def generate_itinerary_pdf(location, days, start_date, itinerary_data, hotels):
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, 
        pagesize=A4, 
        rightMargin=50, 
        leftMargin=50, 
        topMargin=40, 
        bottomMargin=60
    )
    
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontSize=22,
        textColor=PRIMARY,
        alignment=2, # Right-aligned
        spaceAfter=0
    )
    
    label_style = ParagraphStyle(
        'LabelStyle',
        parent=styles['Normal'],
        fontSize=10,
        textColor=GRAY,
        fontWeight='bold',
        leftIndent=5
    )

    subtitle_style = ParagraphStyle(
        'SubtitleStyle',
        parent=styles['Normal'],
        fontSize=11,
        textColor=GRAY,
        spaceAfter=20
    )

    section_header_style = ParagraphStyle(
        'SectionHeaderStyle',
        parent=styles['Heading2'],
        fontSize=18,
        textColor=DARK,
        spaceBefore=20,
        spaceAfter=15,
        borderPadding=5
    )
    
    day_header_style = ParagraphStyle(
        'DayHeaderStyle',
        parent=styles['Heading2'],
        fontSize=20,
        textColor=PRIMARY, # Orange for Days
        spaceBefore=25,
        spaceAfter=15,
        borderPadding=5
    )
    
    place_name_style = ParagraphStyle(
        'PlaceNameStyle',
        parent=styles['Normal'],
        fontSize=14,
        leading=18,
        textColor=DARK,
        spaceBefore=10
    )

    desc_style = ParagraphStyle(
        'DescStyle',
        parent=styles['Normal'],
        fontSize=11,
        textColor=GRAY,
        leftIndent=15,
        italic=True,
        spaceAfter=8
    )

    elements = []

    # ════════════════════════════════════════════════════════════════════════
    # HEADER (Clean Logo + UI-Matched Title)
    # ════════════════════════════════════════════════════════════════════════
    logo_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), "assets", "travelbnb_logo_clean.png")
    
    # Left Side: Logo + Label
    left_side_elements = []
    if os.path.exists(logo_path):
        logo_img = Image(logo_path, width=150, height=38)
        left_side_elements.append(logo_img)
    else:
        left_side_elements.append(Paragraph("<b>Travel</b><font color='#FF6B00'>BNB</font>", title_style))
    
    left_side_elements.append(Paragraph("|  AI PLANNER", label_style))
    
    # Combine logo and label in a sub-table for alignment
    left_side_table = Table([[left_side_elements[0], left_side_elements[1]]], colWidths=[155, 75])
    left_side_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (1, 0), (1, 0), 0),
        ('ALIGN', (0, 0), (0, 0), 'LEFT'),
    ]))

    # Main Header Table: Left (Logo+Label) | Right (Title)
    loc_clean = clean_text(location)
    header_data = [[left_side_table, Paragraph(f"AI Travel Planner – {loc_clean}", title_style)]]
    header_table = Table(header_data, colWidths=[230, 270])
    header_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ALIGN', (0, 0), (0, 0), 'LEFT'),
        ('ALIGN', (1, 0), (1, 0), 'RIGHT'),
        ('LEFTPADDING', (0, 0), (-1, -1), 0),
    ]))
    
    elements.append(header_table)
    elements.append(Spacer(1, 5))
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.lightgrey, spaceAfter=8))
    elements.append(Paragraph(f"Duration: {days} Days  |  Start Date: {start_date}  |  Official Travel Report ✈️", subtitle_style))
    elements.append(Spacer(1, 15))

    # ════════════════════════════════════════════════════════════════════════
    # TRANSPORT LOGISTICS
    # ════════════════════════════════════════════════════════════════════════
    plan = itinerary_data.get("plan", {})
    transport = itinerary_data.get("transport", {})

    elements.append(Paragraph("📍 Travel Logistics", section_header_style))
    
    logistics_data = [
        ["Nearest Airport", clean_text(transport.get('airport', 'Not Available'))],
        ["Railway Hub", clean_text(transport.get('railway', 'Not Available'))]
    ]
    logistics_table = Table(logistics_data, colWidths=[150, 350])
    logistics_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), LIGHT_GRAY),
        ('TEXTCOLOR', (0, 0), (0, -1), DARK),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ('PADDING', (0, 0), (-1, -1), 10),
    ]))
    elements.append(logistics_table)
    elements.append(Spacer(1, 10))

    # ════════════════════════════════════════════════════════════════════════
    # DAILY ITINERARY
    # ════════════════════════════════════════════════════════════════════════
    for day_label, activities in plan.items():
        day_clean = clean_text(day_label)
        elements.append(Paragraph(f"🗓️ {day_clean}", day_header_style))
        
        daily_cost = 0
        
        for activity in activities:
            if isinstance(activity, str):
                act_clean = clean_text(activity)
                if "Estimated Cost" in act_clean:
                    try:
                        cost_val = "".join(filter(str.isdigit, act_clean))
                        if cost_val: daily_cost = int(cost_val)
                    except:
                        pass
                else:
                    elements.append(Paragraph(f"• {act_clean}", styles['Normal']))
                continue
            
            # Place details
            p_name = clean_text(activity.get("place_name", "Unknown Place"))
            p_rating = clean_text(activity.get("rating", "N/A"))
            p_time = clean_text(activity.get("visit_time", "N/A"))
            p_desc = clean_text(activity.get("short_description", ""))
            
            elements.append(Paragraph(f"<b>📍 {p_name}</b>", place_name_style))
            elements.append(Paragraph(f"⭐ {p_rating} Rating  |  ⏱️ {p_time} Hours Visit Time", styles['Normal']))
            if p_desc:
                elements.append(Paragraph(p_desc, desc_style))
            
            # Transport Fares
            transport_fares = activity.get("transport_fares")
            if transport_fares:
                def _fare_display(val):
                    v = clean_text(val)
                    return "❌ Local Only" if v == "Not Available" else v

                fare_data = [
                    ["Vehicle Type", "Estimated Fare/Info"],
                    ["Auto Rickshaw", _fare_display(transport_fares.get("auto", "N/A"))],
                    ["Ola Car", _fare_display(transport_fares.get("ola_car", "N/A"))],
                    ["Uber Car", _fare_display(transport_fares.get("uber_car", "N/A"))],
                    ["Rapido Bike", _fare_display(transport_fares.get("rapido_bike", "N/A"))],
                ]
                fare_table = Table(fare_data, colWidths=[150, 350])
                fare_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), PRIMARY),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
                    ('FONTSIZE', (0, 0), (-1, -1), 10),
                    ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#FFF7ED")]) # Light orange
                ]))
                elements.append(fare_table)
                
                surge = clean_text(transport_fares.get("surge_note"))
                if surge and surge != "N/A":
                    elements.append(Paragraph(f"<i>⚡ Tip: {surge}</i>", ParagraphStyle('small', parent=styles['Normal'], fontSize=9, textColor=GRAY)))
                elements.append(Spacer(1, 10))

            # Nightlife (only if present)
            nightlife = activity.get("nightlife_info")
            if nightlife:
                nl_data = [
                    ["🌃 Nightlife Details", ""],
                    ["Venue", clean_text(nightlife.get("venue_type", "N/A"))],
                    ["Costs", f"Drinks: {clean_text(nightlife.get('avg_drinks_price', 'N/A'))} | Cover: {clean_text(nightlife.get('cover_charge', 'N/A'))}"],
                    ["Vibe", f"{clean_text(nightlife.get('music_genre', 'N/A'))} | {clean_text(nightlife.get('dress_code', 'N/A'))}"],
                    ["Timings", clean_text(nightlife.get("club_timings", "N/A"))],
                ]
                nl_table = Table(nl_data, colWidths=[140, 360])
                nl_table.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), DARK),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('SPAN', (0, 0), (-1, 0)),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
                    ('FONTSIZE', (0, 0), (-1, -1), 10),
                    ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, LIGHT_GRAY])
                ]))
                elements.append(nl_table)
                elements.append(Spacer(1, 10))

        elements.append(Paragraph(f"💰 <b>Estimated Daily Local Spend:</b> ₹{daily_cost}", styles['Normal']))
        elements.append(Spacer(1, 20))

    # ════════════════════════════════════════════════════════════════════════
    # RECOMMENDED HOTELS
    # ════════════════════════════════════════════════════════════════════════
    if hotels:
        elements.append(PageBreak())
        elements.append(Paragraph("🏨 Premium Hotel Suggestions", section_header_style))
        
        hotel_data = [["Hotel Name", "Price (per night)", "Rating"]]
        for hotel in hotels:
            hotel_data.append([
                clean_text(hotel.get("name", "N/A")),
                f"₹{clean_text(hotel.get('price', 'N/A'))}",
                f"⭐ {clean_text(hotel.get('rating', 'N/A'))}"
            ])
        
        t = Table(hotel_data, colWidths=[240, 160, 100])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), PRIMARY),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#FFF7ED")])
        ]))
        elements.append(t)

    # ════════════════════════════════════════════════════════════════════════
    # TRAVEL TIPS
    # ════════════════════════════════════════════════════════════════════════
    elements.append(Spacer(1, 40))
    elements.append(Paragraph("💡 Global Travel Tips", section_header_style))
    tips = [
        "<b>Clothing:</b> Carry light breathable clothing and comfortable walking shoes.",
        "<b>Documents:</b> Keep digital copies of your ID and this itinerary on your phone.",
        "<b>Safety:</b> Always check local weather and news updates before heading out.",
        "<b>Sustainability:</b> Carry a reusable water bottle and respect local customs."
    ]
    for tip in tips:
        elements.append(Paragraph(f"• {tip}", styles['Normal']))
        elements.append(Spacer(1, 5))

    doc.build(elements, onFirstPage=add_footer, onLaterPages=add_footer)
    buffer.seek(0)
    return buffer
